### ISSUE TITLE
Update aws-sdk-go to at least v1.23.13 for OIDC web identity token

### ISSUE THREAD

**Issue by mycrEEpy** [harlow/kinesis-consumer#117]
When using the `kinesis-consumer` library in EKS it's best practice to use OIDC web identity token for authentication to AWS.

We need a minimum aws-sdk-go version of v1.23.13 to use [this feature](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html)

Latest version (as of now) would be [v1.33.1](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.1)

**Comment by harlow** [comment]
Let’s get the AWS SDK updated and cut a new tag
