### ISSUE TITLE
ErrSkipCheckpoint is not functioning

### ISSUE THREAD

**Issue by AkiraTamai** [harlow/kinesis-consumer#136]
Nice to meet you, here is the issue report.

I think that not enabled to skip SetCheckpoint in the case of ScanFunc return value(ErrSkipCheckpoint).

The following code was confirmed.

[master/consumer.go#L202-L210](https://github.com/harlow/kinesis-consumer/blob/master/consumer.go#L202-L210)
![image](https://user-images.githubusercontent.com/1375301/128880113-0fa7c47e-e2c5-4db5-9dbd-6734f1349508.png)

**Comment by tamai-cg** [comment]
Sorry. I was mistaken. Please close. functioning.

**Comment by harlow** [comment]
Thanks for the note 👍
