### ISSUE TITLE
Update to or support AWS SDK v2

### ISSUE THREAD

**Issue by akrantz01** [harlow/kinesis-consumer#138]
Would it be possible to either update to or add support for the new [AWS Go SDK v2](https://aws.github.io/aws-sdk-go-v2/docs/)?

It may be possible to add support by creating an interface that matches both the v1 and v2 versions of the Kinesis client. However, there would undoubtedly need to be some in-between types that might cause issues, especially for the public API staying backward-compatible.

Alternatively, would it be worth making a new major version of kinesis-consumer that supports the v2 SDK?

**Comment by harlow** [comment]
Yeah great call. Will take a look

**Comment by harlow** [comment]
I have a WIP branch running; looking like it's going to be a pretty hefty update. Hopefully can keep it backwards compatible but might need to cut a new version of the lib

**Comment by akrantz01** [comment]
Sounds good. Thanks for working on this! :smiley:

**Comment by aabouelleil-seniorlink** [comment]
Just +1'ing this because we also have a need for a V2 compatible version. Is there any ETA on the update?
