### ISSUE TITLE
aws sdk v2 upgrade 

### ISSUE THREAD

**Issue by polanskya** [harlow/kinesis-consumer#145]
Any idea if this is still blocked?

https://github.com/awslabs/kinesis-aggregation/tree/master/go/v2

Looks like kinesis-aggregation has v2 version

**Comment by harlow** [comment]
nice catch. the `main` branch now uses AWS SDK V2, and this will now use the upstream aggregation library

**Comment by jporcelli1120** [comment]
Am I missing something? I don't see a main branch?

**Comment by der-eismann** [comment]
Will there be a new release anytime soon? Maybe in addition with a rename of `master` to `main`. Or is this project no longer being maintained?
