### ISSUE TITLE
where did version v0.3.6-0.20210911031324-5a873d6e9fec go?

### ISSUE THREAD

**Issue by timo** [harlow/kinesis-consumer#147]
Hi,

I'm in the enviable(?) position to want to make a reproduced build of telegraf for debugging purposes, and version 1.23.2 of telegraf depends on version 0.3.6 of this repository, but the highest release is 0.3.5. I could also not find a commit with the hash given in the version name.

**Comment by bohell** [comment]
same problem.... how can I resolve it?

**Comment by luckyfunky** [comment]
Bump. Same problem. This breaks the build for [telegraf](https://github.com/influxdata/telegraf) in v1.22.x

**Comment by mskonovalov** [comment]
Not sure what happened here, maybe it was a force-push or maybe Telegraf pointed to a PR branch instead of master :(
Anyway, I don't think we can do anything about it now.
