### ISSUE TITLE
Release master changes

### ISSUE THREAD

**Issue by ODudek** [harlow/kinesis-consumer#151]
Hi,

I'm having trouble using the assume-role functionality in version [v0.3.5](https://github.com/harlow/kinesis-consumer/releases/tag/v0.3.5) of the kinesis-consumer library. Specifically, the interface in the WithClient option is incompatible with sdk-v2, which is causing issues for my project. I noticed that this issue has been fixed in the master branch of the repository, so I was wondering if you could release a new version of the library that includes this fix.

If that's not possible, do you have any suggestions for how I can resolve this issue? I'm open to updating my code or using a different version of the library if that will help. Thanks for your help!

**Comment by mskonovalov** [comment]
I know it is a bit late here :)
But just in case somebody else get there in the future
In GoLang you don't really need a specific version to use the latest changes, you can instead point to a specific commit in master (or latest commit in master).
To do that you need to call something like
```
go get github.com/harlow/kinesis-consumer@master
```
and it will get the latest commit
