### ISSUE TITLE
Retryable errors don't get retried in master

### ISSUE THREAD

**Issue by jtackaberry** [harlow/kinesis-consumer#152]
`isRetriableError()` is broken in master which causes retryable errors to abort.  Basically this function needs to look something like:

```go
func isRetriableError(err error) bool {
	var apiErr smithy.APIError
	if !errors.As(err, &apiErr) {
		return false
	}
	switch apiErr.(type) {
	case *types.ExpiredIteratorException:
		return true
	case *types.ProvisionedThroughputExceededException:
		return true
	default:
		return false
	}
}
```

I can submit a PR but it's not entirely clear whether this project is dead or not, so I'll wait for signs of life before investing the effort. :)

**Comment by mskonovalov** [comment]
I guess this is fixed now in https://github.com/harlow/kinesis-consumer/pull/159
