### ISSUE TITLE
Add buffer to DDB Checkpoint

### ISSUE THREAD

**Issue by harlow** [harlow/kinesis-consumer#39]
Been struggling a little with what the "right" solution is for checkpointing.

There were a few options:

1. Checkpoint after each record is processed successfully 
2. Checkpoint when the "cancel" has been sent to pipeline

These have some competing issues: 

* If we checkpoint after each record the backend will need to be able to handle a ton of traffic (not a problem for Redis), but will create hot shard issue for DDB.

* If we only checkpoint when pipeline is shut down then there is a possibility that a checkpoint might be missed if the scan is not shutdown correctly.

The initial implementation leverages the first option and checkpoints after each record is processed, however I think this will cause issues with DDB checkpoint; so need to figure out if the checkpoints can be buffered to DDB (as impl detail of that checkpoint)

https://github.com/harlow/kinesis-consumer/blob/master/consumer.go#L181-L184

**Comment by ligustah** [comment]
The KCL from amazon leaves the decision of when to checkpoint to the actual handler/consumer. I think it makes sense in so far as it depends mostly on your application's specific requirements. For some high volume applications checkpointing on a time interval may be the best option, while other applications might need to checkpoint after each individual record.

**Comment by harlow** [comment]
Ok cool, that sounds totally reasonable. So maybe the setup can look something like this:

```
ck, err := ddbcheckpoint.New(
  ddbcheckpoint.WithMaxDuration(1 * time.Minute),
  ddbcheckpoint.WithMaxRecords(1000),
)
```

Then the checkpoint implementation will be responsible for flushing when the thresholds are met.

```
err := c.checkpoint.Set(c.streamName, shardID, *r.SequenceNumber)
```

For the DDB case the `Set` could add to the buffer and the checkpoint will be responsible for flushing the buffer.

Feels like an additional `Close` func might be nice part of the interface then which signals that the pipeline is shutting down and any remaining state in the buffer should be flushed.
