### ISSUE TITLE
support for more granular return values from the consumer callback function

### ISSUE THREAD

**Issue by melugoyal** [harlow/kinesis-consumer#43]
right now, the only way to not checkpoint a record is to return false from the callback function passed to the consumer. this also ends the scan for that shard. however, there are times when a consumer will want to not checkpoint, but continue scanning the shard. this would be useful if there was an error processing that particular record but there are more records to process in that shard. 

this could be easily fixed by the callback function returning two values: one saying whether to keep processing messages, and one saying whether the processed message should be checkpointed

**Comment by etsangsplk** [comment]
@harlow
Marked this issue solved and the associated PR closed??
