### ISSUE TITLE
Usage of `withClient()`

### ISSUE THREAD

**Issue by mikeholmesuk** [harlow/kinesis-consumer#45]
Hi,

Firstly, thanks for putting this library together and releasing it. The efforts are much appreciated 👍 

Secondly, I'm a relative newcomer to `go` so please forgive any ignorance I may display in asking this. I have a question about the usage of `withClient()`. Looking at the docs it seems to suggest that I can create a new `kinesis` client (as in from `github.com/aws/aws-sdk-go/service/kinesis.Kinesis`) and then pass that in to `getClient()` which is perfect for what I'm trying to do (I have some custom session config on my Kinesis Client). However, the type of the above client is obviously incorrect and as such I can't pass it in (it requires `consumer.Client`). 

I suspect I'm missing a step somewhere?

**Comment by pims** [comment]
I’m having the same issue.

The following code doesn't not let us configure the underlying Kinesis client:

```go
func NewKinesisClient() *KinesisClient {
	svc := kinesis.New(session.New(aws.NewConfig()))
	return &KinesisClient{svc}
}
```

it’d work if we could pass in the `kinesis.Kinesis` dependency ourselves. Something like:

```go
// NewKinesisClient returns client to interface with Kinesis stream
func NewKinesisClient(svc *kinesis.Kinesis) *KinesisClient {
	return &KinesisClient{svc}
}
```

that way, we can configure it however we need.

Another option would be to make `svc` publicly accessible

```go
// KinesisClient acts as wrapper around Kinesis client
type KinesisClient struct {
	Svc *kinesis.Kinesis
}
```

Happy to submit a PR if you think it's a good approach.

**Comment by harlow** [comment]
hopefully w/ #46 merged this issue should be addressed. feel free to re-open if anything else arises

**Comment by diogoo296** [comment]
Hello,

I'm also new to Go but I believe I'm experiencing the same issue.

Here is my code (following the docs to [override the Kinesis client](https://github.com/harlow/kinesis-consumer#client)):

```
package main

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/kinesis"
	consumer "github.com/harlow/kinesis-consumer"
)

func main() {
	// client
	client := kinesis.New(session.New(aws.NewConfig()))
	// consumer
	c, err := consumer.New("mystream", consumer.WithClient(client))
}
```

Which returns the following error:

```
cannot use client (type *kinesis.Kinesis) as type consumer.Client in argument to consumer.WithClient:
	*kinesis.Kinesis does not implement consumer.Client (wrong type for GetRecords method)
		have GetRecords(*kinesis.GetRecordsInput) (*kinesis.GetRecordsOutput, error)
		want GetRecords(context.Context, string, string, string) (<-chan *kinesis.Record, <-chan error, error)
```
