### ISSUE TITLE
Logging, new Logger interface

### ISSUE THREAD

**Issue by imaramos** [harlow/kinesis-consumer#57]
This is more a question than a  issue
I have noticed that recent changes on logging created the need to implement the interface
`// A Logger is a minimal interface to as a adaptor for external logging library to consumer
type Logger interface {
	Log(...interface{})
}` 
Why not follow the convention and use Println() or even Info() in order to avoid the need of 
creating a wrapper that as the Log method?
Thank you for you attention.

Regards

**Comment by etsangsplk** [comment]
There is a lack of consensus of what logger looks like the standard one provided by go is different from alog, uber zap log & glog (some of that doe snot have Println implemented for example, all of which are in use at my place), which people want to use for their own project whatever reasons.
So this adapter is at least give user a choice. Yea I know it is a bit of a mark there too on the wrapper, but improve upon it.

**Comment by imaramos** [comment]
Right but perhaps a more common method should be easier because on exceptions like you mentioned we can make a wrapper, but most of the times you wouldnt need it. Dont you agree?

**Comment by etsangsplk** [comment]
On the contrary, we never use the standard logger but as a fallback as a last resort, all normal logging goes to  some  with higher performance (GC etc) etc.

So if you find a way that neither side need to change code that will be great.

**Comment by harlow** [comment]
> Why not follow the convention and use Println() or even Info() in order to avoid the need of
> creating a wrapper that as the Log method?

Yep, tend to agree w/ that sentiment. 

Looking around a little I found this which resonates with the comments from @etsangsplk 
https://github.com/go-log/log#rationale

**Comment by imaramos** [comment]
I understand @etsangsplk, and you are right, there isnt a standard out there. 
At least perhaps the most used libraries have the "Info" melthod and perhaps it could do here(not saying this would be the best thig to do).
https://github.com/sirupsen/logrus/blob/master/logger.go
https://github.com/golang/glog/blob/master/glog.go
https://github.com/op/go-logging/blob/master/logger.go
https://github.com/apex/log/blob/master/logger.go

**Comment by etsangsplk** [comment]
@imaramos 
That was also my initial reaction when I did that PR.  I did not like the adaptor either myself either.
 At that point, it was more like get that done with as little code as possible , looks like others are using similar pattern (delegate to crowd wisdom), does not involve big change in the kinesis consumer repo itself (since it is not my repo and others are using it). 
As long as it does not involve end user to do lots of work and have the freedom to choose their owner logger for whatever reason. I am all for it. Improvement is very welcome.

**Comment by vincent6767** [comment]
@etsangsplk 
I am wondering what is the LoggerFunc used for in the commit: 739e9e39a585370c09c21aca94afc96b47225b22. I want to add a comment but I am not quite sure what's the purpose.

**Comment by etsangsplk** [comment]
@vincent6767 put my comment there
https://github.com/harlow/kinesis-consumer/commit/739e9e39a585370c09c21aca94afc96b47225b22

**Comment by vincent6767** [comment]
@etsangsplk Thank you for the notification.
