### ISSUE TITLE
Use aws api that accepts context as first parameter.  Opentracing integration requires context as first parameter for propagation

### ISSUE THREAD

**Issue by etsangsplk** [harlow/kinesis-consumer#67]
Opentracing relies on context that encap span metadata inside context to flow through in or out of process boundaries, components etc
I understand that that means breaking change, AWS SDK go offers a parallel set of API that incoporates ...WithContext. See below
https://github.com/aws/aws-sdk-go/blob/master/service/cloudformation/cloudformationiface/interface.go

Or you can carry context in the structure and add WithContext method, which is not quite golang idiom.

opentracing:

example
https://github.com/jaegertracing/jaeger/tree/master/examples/hotrod
https://github.com/jaegertracing/jaeger-client-go

**Comment by harlow** [comment]
hi @etsangsplk can you give a code example of where you'd like to pass the context? i'm fine w/ a breaking change if it makes the library easier to work with and encourages good metrics

**Comment by etsangsplk** [comment]
Found a way to hook into aws session,
https://github.com/harlow/kinesis-consumer/pull/72

**Comment by etsangsplk** [comment]
Close until PR status is known

**Comment by harlow** [comment]
Hi @etsangsplk while overall I think https://github.com/harlow/kinesis-consumer/pull/72 looks good. I've been trying to get my head around if we need all the open-tracing code scattered around the repo. Or if there is a way to have a `Tracer` interface that we can optionally pass in (like we do w/ Counter, Logging, Etc)

**Comment by etsangsplk** [comment]
@harlow there are a few things here:  1) whether you want context is useful as the first parameter; for example if cancellation is on the radar, lots of work would have been done. 2) tracing is stil quite manual and it is more conventional to have user to explicitly deal with spans and packaged such into context to the next level. That also implies following the convention of havinf context as first parameter 3)And opentracing api is an abstraction for tracer and also internally will always look for a singleton globaltracer which defaults to Noop tracer if tracing is “disabled”. All span Operations is Noop if Span cannot be derived from context passed in. I am unsure passing in a tracer is better. For logger you can have multiple loggers, for tracer under opentracing api it is limited by the singleton globaltracer.
