### ISSUE TITLE
Cancelation when one of the Shards is closed

### ISSUE THREAD

**Issue by imaramos** [harlow/kinesis-consumer#78]
https://github.com/harlow/kinesis-consumer/blob/2f58b136fee036f5de256b81a8461cc724fdf9df/consumer.go#L146

The cancel in this line is intended? Doing this cancel() we will cancel all ScanShard routines, even if one of them returned nil because the shard was closed.

Example: 
We have the folowing routines:
ScanShard (shard1)
ScanShard(shard2)

If the shard1 is closed  then the routine returns nil and then we are canceling  the routine ScanShard(shard2), because they share the same context.
Is this intended?

**Comment by imaramos** [comment]
@harlow I did this change https://github.com/imaramos/kinesis-consumer/commit/0a132b1b5320f1bc1cf9a748dac74fc87eb53f0b, but I am not sure if it is the right solution.

**Comment by harlow** [comment]
interesting; yeah good catch. I think this must be a bug. I don't think it makes sense to cancel unless an error has occurred.

**Comment by imaramos** [comment]
So can you fix it or do you prefer me doing a PR?
