### ISSUE TITLE
getShardIDs returns 100 shards at max

### ISSUE THREAD

**Issue by lordfarhan40** [harlow/kinesis-consumer#80]
getShardIDs use "DescribeStream" just once which in turn only return 100 shards at max.
We need to call DescribeStream a few times to get all the shards, something like this [Retrieving Shards](https://docs.aws.amazon.com/streams/latest/dev/kinesis-using-sdk-java-retrieve-shards.html)
**Reference:**
https://github.com/aws/aws-sdk-go/blob/master/service/kinesis/api.go#L3891

**Comment by harlow** [comment]
nice catch, so it looks like `ListShards` supports pagination

```
{
   "ExclusiveStartShardId": "string",
   "MaxResults": number,
   "NextToken": "string",
   "StreamCreationTimestamp": number,
   "StreamName": "string"
}
```

Which means that we could loop over the pages of shards

**Comment by lordfarhan40** [comment]
Yes, we can iterate over the response and keep adding the shards. I will start working on the fix.
