### ISSUE TITLE
Start from the ending of the stream each time

### ISSUE THREAD

**Issue by CcccFz** [harlow/kinesis-consumer#84]
Thank you for your great work !  

When checkpoint is no-op, is the consumer any way to start from **the ending of the stream** each time it is re-started ?

Thank you.

**Comment by harlow** [comment]
Hi, thanks for the question. Sorry for the tardy reply. 

Here are the options for where to start in the stream:
https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetShardIterator.html

The current default behavior is to start at the beginning of the stream:
https://github.com/harlow/kinesis-consumer/blob/master/consumer.go#L30

> TRIM_HORIZON - Start reading at the last untrimmed record in the shard in the system, which is the oldest data record in the shard.

If you'd like to read from the latest point in the stream you'd need to pass that into the config:

> LATEST - Start reading just after the most recent record in the shard, so that you always read the most recent data in the shard.

```go
c, err := consumer.New(
  *stream,
  consumer.WithShardIteratorType(kinesis.ShardIteratorTypeLatest)
)
```

**Comment by CcccFz** [comment]
@harlow  Thanks for your reply. 
It works as you say. I'm closing this issue for now, thanks.
