### ISSUE TITLE
GetRecords Errors are Masked

### ISSUE THREAD

**Issue by jasonpepper** [harlow/kinesis-consumer#92]
I initially ran this against a stream for which I did not have GetRecords permission. So the GetRecords call would fail, but the GetShardIterator call would succeed. And it would repeat this over and over. Eventually, I would receive a ProvisionedThroughputExceededException. But since there were no log messages for the GetRecords errors, I had a lot of trouble figuring out why it was failing. I suggest you log any errors returned from GetRecords.

**Comment by harlow** [comment]
Great catch; so I believe this issue is caused here:
https://github.com/harlow/kinesis-consumer/blob/master/consumer.go#L149-L150

So instead of immediately calling `c.getShardIterator` we should check the error type and if it's non-recoverable then exit.
