### ISSUE TITLE
It wont work if I have no permissions to ListShardsInput

### ISSUE THREAD

**Issue by dema501** [harlow/kinesis-consumer#94]
Hello

I use assume role to initiate session to kinesis from different account and it has very strict access policy.

So, when I call kinesis.ListShardsInput I've got an error and everything stops working

but, good things is I know shardID =1  that I can listen ...
and when hardcode returns in consumer.listShards everything starts working for me...

I wonder if you can add callback func for listShards to AllGroup struct that I can pass  rather then call listShards directly from module which I can't override...

I'm talking about this line https://github.com/harlow/kinesis-consumer/blob/7018c0c47e2ec7c46e1c5c090071f5c40376cac1/allgroup.go#L77

Another case I see if I want to listen just one shard not all them there are no way to do so...

**Comment by harlow** [comment]
Hi @dema501 thanks for submitting these issues. Lemme put some thought into this one, the `AllGroup` is a recent addition and I expect there will be some moving parts over the next week or two. 

> but, good things is I know shardID =1 that I can listen ...

are you passing a slice of ID's?

**Comment by harlow** [comment]
I added a `WithGroup` option so you can provide your own group: https://github.com/harlow/kinesis-consumer/commit/5da0865ac1895bacf8de435bc6f39c9b311d2012

Wondering if you could do something like this:

```go
// list of shards
myShards := []string{
  "shard-1",
  "shard-2",
}

// implement your own group
type staticGroup struct {
	myShards []string
	consumer.Store
}

// implement the `Start` func which appends your shardIDs onto channel
func (sg staticGroup) Start(ctx context.Context, shardc chan *kinesis.Shard) {
	for _, shardID := range sg.myShards {
		shardc <- &kinesis.Shard{ShardId: &shardID}
	}
}


group := &staticGroup{myShards: myShards, Store: myStore}

// consumer
c, err := consumer.New(
  *stream,
  consumer.WithGroup(group),
)
```

**Comment by harlow** [comment]
Going to close this for time being. Feel free to re-open if the `staticGroup` idea doesn't work
